### ISSUE TITLE
Inconsistency between 64px and 84 datasets

### ISSUE THREAD

**Issue by yihaosun1124** [conglu1997/v-d4rl#10]
Thanks for the lovely open-source benchmark. However, I noticed inconsistencies between the 64px and 84px datasets. Specifically, I observed that the number of transitions in the 64px dataset is less than in the 84px one. For instance, the cheetah_run_medium_replay dataset in 84px has 200k transitions (which aligns with the description in your paper), but the 64px version only has 50k. I'm wondering if you might have missed uploading some of the data for the 64px version.

**Comment by conglu1997** [comment]
Hey! How are you computing this?

I just checked https://drive.google.com/drive/folders/1xAcRdQHgZlcs2tTcLQNOT_wMO-bm3w44?usp=drive_link and there are 400 files each with 1 episode each (500 steps in each).
