### ISSUE TITLE
Generating Humanoid Dataset

### ISSUE THREAD

**Issue by gunnxx** [conglu1997/v-d4rl#11]
Hi, this might be not the place but I am just wondering what hyperparameters did you use to train the SAC agent (data collection policy) for Humanoid Walk? The default hyperparameters successfully achieve expert level performance for 1M steps for Walker Walk and Cheetah Run. I use [this codebase](https://github.com/philipjball/SAC_PyTorch/blob/dmc_branch/train_agent.py) as mentioned in the README.

**Comment by conglu1997** [comment]
I believe you'll need 10M steps for expert on that environment.

**Comment by gunnxx** [comment]
Okay noted. Thanks a lot for the quick reply, appreciate it!
