### ISSUE TITLE
About the corresponding proprioceptive states for the dataset

### ISSUE THREAD

**Issue by linkct** [conglu1997/v-d4rl#14]
Hi, thank you for this great work! I noticed that the visual observations are generated by a proprioceptive SAC agent, but could not find the states corresponding to the images in the downloaded dataset; is it possible to acquire the proprioceptive states somewhere? I saw the behavior agent training script in the README, but it seems hard to deterministically reproduce the training / data collection process, as various sources of randomness are present. Thank you for your time!

**Comment by conglu1997** [comment]
Hi, we do not have these saved, sorry! The data collection should be reproducible with fixed seed=0. Cheers!
