### ISSUE TITLE
Is image observation of the Franka Kitchen dataset supported?

### ISSUE THREAD

**Issue by BrightMoonStar** [conglu1997/v-d4rl#16]
Hi~
I want  to know whether image observation of the Franka Kitchen dataset supported?
Thank you ！

**Comment by conglu1997** [comment]
Hi! Yes, of course. You may need to change the size of the encoder, let me know if you need help!

**Comment by BrightMoonStar** [comment]
I'm very sorry that I couldn't find the relevant dataset of Franka Kitchen on hugging face or Google Drive, and there doesn't seem to be Franka Kitchen in the list of this previous reply.
https://github.com/conglu1997/v-d4rl/issues/5#issuecomment-1732234639

**Comment by conglu1997** [comment]
We have no Franka dataset. If you had your own Franka dataset, you would be able to use our algorithms with it!
