### ISSUE TITLE
Only 50K data for 64px in hugging face

### ISSUE THREAD

**Issue by GGOSinon** [conglu1997/v-d4rl#17]
It seems that there is only 100 npz files in hugging face (while 400 npz files are in Google drive)

Can you update the hugging face repository?

**Comment by conglu1997** [comment]
Which folder?

**Comment by GGOSinon** [comment]
For all 3 * 5 folders in the main, as I see.
Example: https://huggingface.co/datasets/conglu/vd4rl/tree/main/vd4rl/main/cheetah_run/medium_replay/64px
