### ISSUE TITLE
Failed to run DrQ+BC evaluation

### ISSUE THREAD

**Issue by levilovearch** [conglu1997/v-d4rl#4]
Dear developer,

Thanks for your work.
I followed your instructions strictly while failed to run DrQ+BC evaluation with the following error:
`Traceback (most recent call last):
  File "drqbc/train.py", line 20, in <module>
    import dmc
  File "/vd4rl/drqbc/dmc.py", line 14, in <module>
    from envs.distracting_control.suite import distracting_wrapper
ModuleNotFoundError: No module named 'envs'`
Have you run into a similar problem before?

Many thanks,
Levi

**Comment by conglu1997** [comment]
Hi, envs simply refers to https://github.com/conglu1997/v-d4rl/tree/main/envs

I would check your PYTHONPATH: https://www.geeksforgeeks.org/pythonpath-environment-variable-in-python/
