### ISSUE TITLE
a complete list of all tasks for V-D4RL

### ISSUE THREAD

**Issue by BlankSHC** [conglu1997/v-d4rl#5]
For all tasks that are prone to confusion, it is recommended to provide a complete list of all tasks for V-D4RL. 
Similar to this https://github.com/Farama-Foundation/d4rl/wiki/Tasks

**Comment by gunnxx** [comment]
They provide it in the paper (Table 5, Appendix A)
![Screenshot from 2023-09-23 15-50-17](https://github.com/conglu1997/v-d4rl/assets/31506965/8fed42bf-0bba-4eac-95ce-b6ca86e35df5)

**Comment by conglu1997** [comment]
Thanks for the helpful comment! :)
