### ISSUE TITLE
Questions about TimeLimit of DMC vision and dataset in pytorch version

### ISSUE THREAD

**Issue by return-sleep** [conglu1997/v-d4rl#9]
Thank you for your outstanding work. May I ask why the timelimit for DMC vision is 0 and not 1000?

![849194b7c38d5dc5aedc43d63787075](https://github.com/conglu1997/v-d4rl/assets/74049270/b19bd700-bd2f-4974-879e-9ad2c97ee21b)

Another thing I'd like to confirm is that in each episode, the first timestep's "action" and "reward" are 0 right, because they're offset by one step from "image"?

Also if I want to change the dataset related code to a pytorch version, how should I make sure it uses the full offline data? In the current code it looks like it selects sub-trajectory randomly.

**Comment by conglu1997** [comment]
Hi,

1. You can verify that the eval environments are 1000 time limit as expected, the configs are copied from the original repo.
2. The observations are offset by one, yes.
3. Selecting n-step subtrajectories are how the recurrent DreamerV2 model is trained, you may wish to refer to a PyTorch implementation of Dreamer if that is what you are looking for.

Hope that helps, cheers!
